--REPORT 3--
--SELECTING LOW-INCOME STUDENT'S COMMUNITY CONCERNS REPORT--
CREATE VIEW STCOMMU
AS
SELECT DISTRICTCODE,LOCALITY,GENDER,ABSENT_DAYS,STDDINT,STDLIV,STDHLTH3,STAGEENG,SCHFAC12,SCHFAC07,HTEXM024,HTEXM051,HTTYPSCH,HTMTHTNG,
HTRELGN,STGR1004
FROM VIET_WAVE1
WHERE GENDER IS NOT NULL

SELECT * FROM STCOMMU

--ANALYSING THE DISTRCT REGIONS RECORD WITH THEIR COUNTS REGARDING CONCERS--
SELECT LOCALITY,DISTRICTCODE, COUNT(*) AS 'COUNT'
FROM STCOMMU
GROUP BY LOCALITY,DISTRICTCODE
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC

--ANALYSING THE GOVERNMENT SCHOOL CONCERS--
SELECT HTTYPSCH,STGR1004,SCHFAC12
FROM STCOMMU
WHERE HTTYPSCH=1 AND STGR1004 IS NOT NULL 
GROUP BY HTTYPSCH,STGR1004,SCHFAC12


--ANALYSING THE LANG AND RELIGION COUNT---
SELECT HTRELGN,HTMTHTNG,COUNT(*) AS 'COUNT'
FROM STCOMMU
GROUP BY HTRELGN,HTMTHTNG
ORDER BY COUNT(*) DESC

