/* CREATING THE TABLES */

--TABLE 1--
CREATE TABLE VIET_WAVE1
(
[UNIQUEID] VARCHAR(40),
[SCHOOLID] INT,
[CLASSID] INT,
[STUDENTID] INT,
[YLCHILDID] VARCHAR(40),
[PROVINCE] INT ,
[DISTRICTCODE] INT ,
[LOCALITY] INT ,
[GENDER] INT ,
[AGE] INT ,
[ETHNICITY] INT ,
[ABSENT_DAYS] INT ,
[MOM_EDUC] INT ,
[DAD_EDUC] INT ,
[STDYLCHD] INT ,
[STDDINT] DATETIME ,
[STDLIV] INT ,
[STDLNGHM] INT ,
[STDHLTH1] INT ,
[STDHLTH2] INT,
[STDHLTH3] INT ,
[STDHLTH0] INT ,
[STPPLHM] INT ,
[STSIBOLD] INT ,
[STSIBYNG] INT ,
[STHVCOMP] INT ,
[STHVINTR] INT ,
[STTMSCH] INT ,
[STAGEENG] INT ,
[STITMOW8] INT ,
[SCHFAC12] INT ,
[SCHFAC09] INT ,
[SCHFAC07] INT ,
[HTEXM024] INT,
[HTEXM051] INT ,
[HTTYPSCH] INT ,
[HTMTHTNG] INT ,
[HTRELGN] INT ,
[STGR1005] INT ,
[STGR1004] INT ,
[STGR1001] INT )

/* INSERTING THE VALUES IN TABLES */

INSERT INTO VIET_WAVE1 
Select UNIQUEID,SCHOOLID,CLASSID,STUDENTID,YLCHILDID,PROVINCE,DISTRICTCODE,LOCALITY,GENDER,AGE,ETHNICITY,ABSENT_DAYS,
MOM_EDUC,DAD_EDUC,STDYLCHD,STDDINT,STDLIV,STDLNGHM,STDHLTH1,STDHLTH2,STDHLTH3,STDHLTH0,STPPLHM,STSIBOLD,STSIBYNG,STHVCOMP,
STHVINTR,STTMSCH,STAGEENG,STITMOW8,SCHFAC12,SCHFAC09,SCHFAC07,HTEXM024,HTEXM051,HTTYPSCH,HTMTHTNG,HTRELGN,
STGR1005,STGR1004,STGR1001
FROM dbo.vietnam_wave_1$;

SELECT * FROM VIET_WAVE1

/* CREATING THE TABLES */

--TABLE 2--
CREATE TABLE VIET_WAVE2
(
[UNIQUEID] VARCHAR(40),
[SCHOOLID] INT,
[CLASSID] INT,
[STUDENTID] INT,
[STDINT] DATETIME,
[STCMPHME] INT ,
[STMTHWRK] INT ,
[STMWRKCH] INT ,
[STRSNMS3] INT ,
[STRSNMS4] INT ,
[STPRVMT] INT ,
[STPRVEN] INT ,
[STFEEL18A] INT ,
[STFEEL18C] INT ,
[STFEEL18I] INT ,
[STFEEL20L] INT ,
[STFEEL22H] INT ,
[STFEEL51] INT ,
[ENG_ITEM1] INT ,
[ENG_ITEM2] INT ,
[ENG_ITEM3] INT ,
[MATH_ITEM1] INT ,
[MATH_ITEM2] INT ,
[MATH_ITEM3] INT ,
[TS_ITEM1] INT ,
[TS_ITEM2] INT ,
[TS_ITEM3A] INT ,
[TS_ITEM3B] INT ,
[TS_ITEM3C] INT )

/* INSERTING THE VALUES IN TABLES */

INSERT INTO VIET_WAVE2 
Select UNIQUEID,SCHOOLID,CLASSID,STUDENTID,STDINT,STCMPHME,STMTHWRK,STMWRKCH,STRSNMS3,STRSNMS4,STPRVMT,STPRVEN,
STFEEL18A,STFEEL18C,STFEEL18I,STFEEL20L,STFEEL22H,STFEEL51,ENG_ITEM1,ENG_ITEM2,ENG_ITEM3,MATH_ITEM1,
MATH_ITEM2,MATH_ITEM3,TS_ITEM1,TS_ITEM2,TS_ITEM3A,TS_ITEM3B,TS_ITEM3C 
FROM dbo.vietnam_wave_2$;

SELECT * FROM VIET_WAVE1

--REPORT 1--
--CREATING THE VIEW ABOUT STUDENT INFO--
CREATE VIEW STUDENTINFO
AS
SELECT ST1.UNIQUEID,ST1.SCHOOLID,ST1.CLASSID,ST1.STUDENTID,ST1.PROVINCE,ST1.DISTRICTCODE,ST1.LOCALITY,
ST1.GENDER,ST1.AGE,ST1.ETHNICITY,ST1.STDLNGHM,ST1.STDHLTH1,ST1.HTMTHTNG,ST1.HTRELGN,ST2.STFEEL18A,ST2.STFEEL18I,ST2.ENG_ITEM1,
ST2.MATH_ITEM1,ST2.TS_ITEM1
FROM VIET_WAVE1 ST1
JOIN VIET_WAVE2 ST2
ON ST1.UNIQUEID=ST2.UNIQUEID;

SELECT * FROM STUDENTINFO

--GETTING THE DATA FOR THE MALE AND FEMALE STUDENTS WITH GRADES IN SUBJECTS--
SELECT * 
FROM STUDENTINFO
WHERE GENDER=1 AND 
ENG_ITEM1 IS NOT NULL AND 
MATH_ITEM1 IS NOT NULL AND 
TS_ITEM1 IS NOT NULL 

SELECT * 
FROM STUDENTINFO
WHERE GENDER=2 AND 
ENG_ITEM1 IS NOT NULL AND 
MATH_ITEM1 IS NOT NULL AND 
TS_ITEM1 IS NOT NULL

--SELECTING THE DATA OF STUDENTS WHO COMES FROM CENTRAL CITY PROVINCE--
SELECT PROVINCE,COUNT(*) AS 'COUNT'
FROM STUDENTINFO
WHERE PROVINCE IS NOT NULL
GROUP BY PROVINCE
ORDER BY PROVINCE DESC

