--REPORT 2--
--SELECTING LOW-INCOME STUDENT'S HOUSEHOLD CONCERNS REPORT--
--CREATING THE VIEW--
CREATE VIEW STHOUSE
AS
SELECT ETHNICITY,MOM_EDUC,DAD_EDUC,STDYLCHD,STDLNGHM,STPPLHM,STSIBOLD,STSIBYNG,STHVCOMP,STHVINTR,STTMSCH,STITMOW8
FROM VIET_WAVE1

SELECT * FROM STHOUSE

--ANALYSING THE LOWEST ETHINIC NUNG GROUP'S PARENT'S EDUCATION CONCERNS-- 
SELECT ETHNICITY,AVG(MOM_EDUC) AS AV_MOM, AVG(DAD_EDUC) AS AV_DAD
FROM STHOUSE 
WHERE ETHNICITY=6 
GROUP BY ETHNICITY,MOM_EDUC,DAD_EDUC
ORDER BY AV_MOM DESC,AV_DAD 

--ANALYSING THE EHTHNICITY GROUP HAVING THE FACILITY OF COMPUTER AND INTERNET AT HOME--
SELECT ETHNICITY,MAX(STHVCOMP) AS MAX_COMP,MAX (STHVINTR) AS MAX_INTERNET 
FROM STHOUSE
WHERE ETHNICITY IS NOT NULL
GROUP BY ETHNICITY
ORDER BY ETHNICITY

